### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by jjdbear** [matteo-rizzo/fc4-pytorch#1]
I got an error massage when I run the training on epoch 106,  it's quite runing while before,  and I want to know if you have ever met this error before. The massage like bellow:

Traceback (most recent call last):
  File "/home/wangjin/miniconda3/envs/videoEnhance/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7fd3454fc320>
Traceback (most recent call last):

Waiting for you answer, thanks.

**Comment by matteo-rizzo** [comment]
Hi! 

That may be a problem related to your matplotlib backend. Please try to modify the matplotlib import at classes.fc4.ModelFC4.py to 

```python
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt 
```

Matplotlib is used to save the visualizations for selected test images at training time. If the fix I suggested does not work for you and you are not interested in those visualizations, an easy workaround could be modifying the list of monitored images (i.e., `TEST_VIS_IMG = ["IMG_0753", "IMG_0438", "IMG_0397"]` in train.py) to an empty list.

Let me know if that solved your problem!

**Comment by jjdbear** [comment]
> Hi!
> 
> That may be a problem related to your matplotlib backend. Please try to modify the matplotlib import at classes.fc4.ModelFC4.py to
> 
> ```python
> import matplotlib
> matplotlib.use('Agg')
> import matplotlib.pyplot as plt 
> ```
> 
> Matplotlib is used to save the visualizations for selected test images at training time. If the fix I suggested does not work for you and you are not interested in those visualizations, an easy workaround could be modifying the list of monitored images (i.e., `TEST_VIS_IMG = ["IMG_0753", "IMG_0438", "IMG_0397"]` in train.py) to an empty list.
> 
> Let me know if that solved your problem!


Now it is runing well with these  codes:
> ```python
> import matplotlib
> matplotlib.use('Agg')
> import matplotlib.pyplot as plt 
> ```
Thanks a lot!
