### ISSUE TITLE
How to use the dataset?

### ISSUE THREAD

**Issue by ToChangeBetter** [matteo-rizzo/fc4-pytorch#10]
(After downloading the data, please extract it and move the images and coordinates folders and the folds.mat file to the dataset folder.)
I can't understand this sentence. I have downloaded this datasets. I don't move this datasets to dataset folder.I think that your work is excellent ! I am looking forward to your reply.
Thanks !

**Comment by ToChangeBetter** [comment]
![image](https://user-images.githubusercontent.com/97652404/162679783-74dd976a-5020-46ef-b6bd-0d570ea777ee.png)

**Comment by ToChangeBetter** [comment]
Whether to download these?

**Comment by matteo-rizzo** [comment]
Hi and thank you for your question! You need to download all of the parts the dataset is divided into and put them in one folder. The folds.mat file and coordinates folder are already provided so you just need to move the images to the dataset folder and run the img2npy.py preprocessing script. I hope this helps!

**Comment by ToChangeBetter** [comment]
![image](https://user-images.githubusercontent.com/97652404/162897274-29ba0cae-1c38-453e-9940-127f2632d9bf.png)

**Comment by ToChangeBetter** [comment]
sorry，I understand your mean.Thanks!

**Comment by ToChangeBetter** [comment]
hello！ you reproduce C4 paper.I have some questions.
![image](https://user-images.githubusercontent.com/97652404/162913359-6c6dffa7-879b-4258-ae41-e6d52df55d41.png)
 I run the run.sh file .it isn't response. And pretrain model can't download.
