### ISSUE TITLE
How to input own pictures for testing

### ISSUE THREAD

**Issue by zhujiaxian** [matteo-rizzo/fc4-pytorch#11]
How to input own pictures for testing

**Comment by matteo-rizzo** [comment]
Hi! Currently, only the ColorChecker dataset is supported. To test the models on your own picture you will need to write your own dataset class to feed to a data loader.

**Comment by ToChangeBetter** [comment]
Do it support  NUS  dataset？

**Comment by matteo-rizzo** [comment]
Hi! Please see the answer above. Thanks!
