### ISSUE TITLE
When I run make_gif.py , it appears FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'vis\\gif_frames_2k_epochs\\IMG_0753'?

### ISSUE THREAD

**Issue by ToChangeBetter** [matteo-rizzo/fc4-pytorch#13]

**Comment by matteo-rizzo** [comment]
Hello! To generate a GIF you want to edit the PATH_TO_IMAGES variable to point to the folder where you stored the saved frames. Hope this helps

**Comment by ToChangeBetter** [comment]
Ok,I understand your sentence. Thanks!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "matteo-rizzo/fc4-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 凌晨4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [matteo-rizzo/fc4-pytorch] When I run make_gif.py , it appears FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'vis\\gif_frames_2k_epochs\\IMG_0753'? (Issue #13)





 
Hello! To generate a GIF you want to edit the PATH_TO_IMAGES variable to point to the folder where you stored the saved frames. Hope this helps
