### ISSUE TITLE
How to train on Multiple GPUs?

### ISSUE THREAD

**Issue by CharlesTran** [matteo-rizzo/fc4-pytorch#14]
Hi, I found it difficult to increase the batch size and I tried to run on multiple gpus but failed. Can you offer some solutions?

**Comment by matteo-rizzo** [comment]
Hi and thank you for your question :)

At the moment, the code I developed is not meant to support multi-GPU training. However, you can try to develop your own fork and refer to this guide to adjust the GPU usage: https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html

**Comment by CharlesTran** [comment]
Thank you for your advice. I've finally made it to support multi-GPU training and I'm willing to share it once I'm done with my work.
