### ISSUE TITLE
No such file or directory: 'dataset\\folds.mat'

### ISSUE THREAD

**Issue by xiangyj50** [matteo-rizzo/fc4-pytorch#17]
Hello, thank you for sharing.

When I was running train.py, I encountered an issue with the image and couldn't find folds.mat. I hope you can help me solve it.
![issue](https://github.com/matteo-rizzo/fc4-pytorch/assets/49711006/e6564f23-df12-4844-984d-ab835934939a)

**Comment by matteo-rizzo** [comment]
Hi! It looks like a path error. Are you sure that "dataset/folds.mat" is a valid path from your root folder?

**Comment by xiangyj50** [comment]
> Hi! It looks like a path error. Are you sure that "dataset/folds.mat" is a valid path from your root folder?

Thank you for your suggestion. My problem has been resolved
