### ISSUE TITLE
Issue with Importing Auxiliary Module in FC4 Model Conversion

### ISSUE THREAD

**Issue by sonainjameel** [matteo-rizzo/fc4-pytorch#19]
Hi,

First off, I want to express my appreciation for the work done on converting the FC4 model from Python 2 to PyTorch. It's a significant contribution, and I'm excited to explore its capabilities.

However, I encountered an issue when attempting to test the model. Specifically, I ran into an import error stating "No module named auxiliary." I've checked my project structure to ensure the auxiliary folder is correctly placed and even considered the absence of an __init__.py file as a potential cause. Despite these checks, the issue persists.

I was wondering if you might have any insights or suggestions on how to resolve this import error. Any guidance or additional documentation on this matter would be greatly appreciated.

Thank you for your support and for the incredible work on this project.

**Comment by matteo-rizzo** [comment]
Hi, and thank you for your interest in the project! Are you running the test script from the root folder or inside the `test` folder? It seems like an issue with the relative/absolute paths of the import. All tests have been performed by running the test from the root folder

**Comment by sonainjameel** [comment]
> Hi, and thank you for your interest in the project! Are you running the test script from the root folder or inside the `test` folder? It seems like an issue with the relative/absolute paths of the import. All tests have been performed by running the test from the root folder

Thank you for the response, I wanna ask if there is any option to test the trained models on the custom images without Colorchecker rather than using the provided test dataset. It would be great if you could provide some insights on this. Thanks.
