### ISSUE TITLE
Hello, I can't find the pretrained model  in the trained_models as you have mentioned.

### ISSUE THREAD

**Issue by Zhi-Feng-Zhang** [matteo-rizzo/fc4-pytorch#2]

**Comment by matteo-rizzo** [comment]
Hi! Sorry about that, I just uploaded them and now you should find them under `trained_models`. Those under `trained_models/fc4_cwp` are meant to be used with **confidence-weighted-pooling activated** while those under  `trained_models/fc4_sum` with **confidence-weighted-pooling not activated**. All models come with a log of the training metrics and a dump of the network architecture.
