### ISSUE TITLE
Question about Reproduced FC4 Results

### ISSUE THREAD

**Issue by a2108870** [matteo-rizzo/fc4-pytorch#20]
Hello,

First of all, thank you for your efforts in reproducing the FC4 code using the Torch framework. 

I have a question regarding the results obtained from your reproduction. I noticed that the reproduced results are different from those reported in the original FC4 paper. For example, the original paper mentions a mean error of 1.65 on the CC dataset's test set, while your reproduced results show a mean error of 1.92. Additionally, it seems that the results for fc_cwp are not as good as those for fc_sum.

Could you please provide some insights into why there might be a discrepancy between the reproduced results and the original paper's results? 

Thank you again for your valuable work, and I look forward to your response.

**Comment by matteo-rizzo** [comment]
Hello. Thank you for your message. I can confirm your observations, but I have little further insight. I could not use the original code to reproduce the results in the original FC4 paper, and I am confident of the quality of my implementation. Their results might be based on just one run over the dataset without cross-validation; thus, the lower error is a lucky strike. Of course, this is just a hypothesis.
