### ISSUE TITLE
[img2npy.py] Expected all tensors to be on the same device, but found at least two devices.

### ISSUE THREAD

**Issue by Hurricane-k** [matteo-rizzo/fc4-pytorch#21]
Hello thank you for ur support of reproducing FC4 on pytorch.

there is some errors I encountered when running `img2npy.py` in VSCode

My PC configuration includes CPU and GPU. 
I used `torch==2.4.1` supporting GPU

in `utils.py` `line 52`
`correction = illuminant.unsqueeze(2).unsqueeze(3) * torch.sqrt(Tensor([3])).to(DEVICE)`
 showing the error in the title.

I changed this line to
`correction = illuminant.unsqueeze(2).unsqueeze(3).to(DEVICE) * torch.sqrt(Tensor([3])).to(DEVICE)`

no idea if you upload the version with only cpu. 

Best Regards,
Carry

**Comment by Hurricane-k** [comment]
another question is about the number of files in `dataset/coordinates`
there are totoally 592 `.txt` files, but I download images following your bio link in `README.md`. There are only 568 images. Would the difference in quality cause error in `img2npy.py`?

Is there anything I missed by accident?

**Comment by matteo-rizzo** [comment]
Hello! Thank you very much for pointing out the issue with the device. I just wanted to let you know that I fixed it accordingly. Unfortunately, I have no clue about the mismatch in the number of coordinates files. My dump came from the same source, but please refer to what has been indicated on the README as that is more reliable. I will try to test this out extensively as soon as possible

**Comment by Hurricane-k** [comment]
Hello 

Thank you for your time and attention. Could you mind if I express it more specifically? Was the folder `./dataset/coordinates` downloaded by [coordiantes](http://www.kyb.mpg.de/bs/people/pgehler/colour/index.html) in [Shi's Re-processing of Gehler's Raw Dataset](https://www2.cs.sfu.ca/~colour/data/shi_gehler/). Since that link is valid, I have no idea about the exact meaning of `*_macbeth.txt`. But I think the total number of these `*_macbeth.txt` files should be equal to the number of images in `Canon 1D` + `Canon 5D(1)` + `Canon 5D(2)` + `Canon 5D(3)`. But I only got 568 `.png` images. but there are 592 `*_macbeth.txt` files. Did I miss anything or I misunderstand something.

Another thing I need to ask about parameters. As we all know, `bath_size` would have a great impact on the final models. If the `batch_size` is set as 1, much randomness would be intorduced in the training process. So if didn't get you wrong, you set `batch_size = 1`, but the original is 10. And I tried to tune this parameter, some error would abort the training process. Would you mind if give me some advice.

Best Regards,
Carry

**Comment by matteo-rizzo** [comment]
Hi, and thank you for your interest. You got it right. That folder was downloaded like you said. That was some time ago though, so I don't know if anything changed on the [Shi's Re-processing of Gehler's Raw Dataset](https://www2.cs.sfu.ca/~colour/data/shi_gehler/) that could justify the mismatch in the number of coordinates. As for the batch size, you are right again. However, I did not implement support for batch size greater than 1. I suspect that would not have much impact on the monitored metrics, but, unfortunately, I do not have time to integrate the functionality. It should be fairly easy to adapt the code accordingly though.

**Comment by Hurricane-k** [comment]
Hi, and thank you for your time and support. I got it.
