### ISSUE TITLE
I can't reset the batch_size ?

### ISSUE THREAD

**Issue by nlpofwhat** [matteo-rizzo/fc4-pytorch#3]
Why I can't reset the batch_size ? when I reset the batch_size to larger ,  there will exist some bugs

**Comment by matteo-rizzo** [comment]
Hi, could you please provide more details about your error (e.g. some log)? Thank you!

**Comment by nlpofwhat** [comment]
Thanks for your reply.I’ve solved my problem.After reading your code more carefully.I found you use different preprocessing method for training and test.During test stage,you only crop the original image,so the size of image would be inconsistent and the batchsize must be 1. To accelerate training ,I need to use different batchsize in training and test.But my another confusion is why the proprecessing is different in trading and test.------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月23日(星期天) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [matteo-rizzo/pytorch-fc4] I can&#39;t reset the batch_size ? (#3)

**Comment by matteo-rizzo** [comment]
Happy to hear your problem has been solved. The training-test processing mismatch is due to data augmentation, which only applies to training instances.
