### ISSUE TITLE
some thing wrong with the correction procedure

### ISSUE THREAD

**Issue by Bright-Shawn** [matteo-rizzo/fc4-pytorch#8]
Very well Pytorch realization, Thank you Matteo!

However, some thing maybe misunderstood about the Color Constancy procedure in ISP

> RAW--->Color Constancy--->Gamma correction 

So in your code, the 'gt_corrected' part may not correct because you used the **After-Gamma** image as an input, which leads to the pure white appearance in images in the 'gt_corrected' folders

'img2npy.py':

**BEFORE**
vis_img = Image.fromarray((_**linear_to_nonlinear**_(bgr_to_rgb(normalize(img_without_mcc))) * 255).astype(np.uint8))
gt_corrected = correct(vis_img, torch.from_numpy(np.array([illuminant])))

**AFTER**
vis_img = Image.fromarray(((bgr_to_rgb(normalize(img_without_mcc))) * 255).astype(np.uint8))
gt_corrected = correct(vis_img, torch.from_numpy(np.array([illuminant])))

**Comment by matteo-rizzo** [comment]
Hi! Thanks for pointing this out, it was an error indeed. I fixed it and made a new release :)
